#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int aqua = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int background_color = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int black = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int blue = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int fuchsia = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int gray = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int green = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int lime = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int maroon = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int navy = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int olive = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int purple = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int red = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int silver = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int teal = 2130968587;
			
			// aapt resource value: 0x7f040012
			public const int textColorHint = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int textInputColor = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int yellow = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int folder_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int email_input = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int login_btn = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int logo = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int password_input = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
